name: 'helllicht/sftp-upload'
description: 'helllicht internal sftp-upload-action'

inputs:
    host:
        description: 'Host (e.g. "my-sftp-url.com")'
        required: true
    port:
        description: 'Port [default: "22"]'
        required: false
        default: '22'
    username:
        description: 'Username'
        required: true
    password:
        description: 'Password'
        required: true
    localDir:
        description: 'Directory that should be uploaded (e.g. ".", "dist", "./app", "./compiled/")'
        required: true
    uploadPath:
        description: 'Path where the working directories are [default: "./"] (e.g. "app", "./www/", "www/prod", "html/var/"'
        required: false
        default: './'
    exclude:
        description: 'Files/Folders that should not be uploaded [default: see action.yml] (it is using regex, so use it wisely!)'
        required: false
        default: '[".github", ".git", ".gitignore", "composer.phar", "node_modules", "README.md", "package.json", "package-lock.json", "yarn.lock"]'
    debugMode:
        description: 'Enable debug ("on"/"off") to receive a detailed log of the upload [default: "off"]'
        required: false
        default: 'off'

runs:
    using: 'node12'
    main: 'dist/index.js'
